export const ROUTES = {
  HOME: '/',
  ANNUAIRE: '/annuaire',
  COMMERCE: (id: string) => `/commerce/${id}`,
  URGENCE: '/urgence',
  FAVORIS: '/favoris',
  CONNEXION: '/connexion',
  INSCRIPTION: '/inscription',
  MOT_DE_PASSE_OUBLIE: '/mot-de-passe-oublie',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  DASHBOARD_COMMERCES: '/dashboard/commerces',
  DASHBOARD_STATISTIQUES: '/dashboard/statistiques',
  DASHBOARD_AVIS: '/dashboard/avis',
  DASHBOARD_PROFIL: '/dashboard/profil',
  ADMIN: '/admin',
  ADMIN_UTILISATEURS: '/admin/utilisateurs',
  ADMIN_COMMERCES: '/admin/commerces',
  ADMIN_COMMENTAIRES: '/admin/commentaires',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_SIGNALEMENTS: '/admin/signalements',
} as const;